config/routes.rb
Polyester::Application.routes.draw do

  get 'pages/claim'
  post 'pages/access'
  get 'pages/products'

  mount Ckeditor::Engine => '/ckeditor'

  resources :vendors, :contacts, :abouts, only: [:index]
  resources :mebels, :cloths, :yarns, :news, only: [:index, :show]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'news#index'

  

end

app/models/about.rb
class About < ActiveRecord::Base
  attr_accessible :text
  has_many :image
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :name, :login, :password, :password_confirmation, :current_sign_in_at, :last_sign_in_at
end

app/models/cloth.rb
class Cloth < ActiveRecord::Base
  attr_accessible :text, :autor, :title
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :text
  has_many :image
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :about
  belongs_to :contact
  belongs_to :vendor
end

app/models/mebel.rb
class Mebel < ActiveRecord::Base
  attr_accessible :text, :autor, :title
end

app/models/new.rb
class New < ActiveRecord::Base
  attr_accessible :text, :autor, :title
end

app/models/page.rb
class Page < ActiveRecord::Base
  validates :mail, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create }, :presence => true
  validates :name, :presence => true
  validates :message, :presence => true
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  attr_accessible :text
  has_many :image
end

app/models/yarn.rb
class Yarn < ActiveRecord::Base
  attr_accessible :text, :autor, :title
end

app/controllers/abouts_controller.rb
class AboutsController < InheritedResources::Base

end

app/controllers/news_controller.rb
class NewsController < InheritedResources::Base
  def index
    @news=New.all
  end

  def show
    @news = New.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < InheritedResources::Base

  def claim
    render 'claim'
  end

  def access
    Pony.mail(:to => 'darkwater666@mail.ru', :from => 'me@example.com', :subject => 'hi', :body => params[:message], :via => :smtp) # sends via SMTP
    render 'access'
  end

  def products
    render 'products'
  end

end

app/controllers/yarns_controller.rb
class YarnsController < InheritedResources::Base
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cloths_helper.rb
module ClothsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/mebels_helper.rb
module MebelsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/yarns_helper.rb
module YarnsHelper
end

app/views/abouts/_form.html.slim
= form_for @about do |f|
  - if @about.errors.any?
    #error_explanation
      h2 = "#{pluralize(@about.errors.count, "error")} prohibited this about from being saved:"
      ul
        - @about.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :text
    = f.cktext_area :text, :ckeditor => {:language => 'ru'}
  .actions = f.submit 'Save'

app/views/abouts/edit.html.slim
h1 Editing about

== render 'form'

= link_to 'Show', @about
'|
= link_to 'Back', abouts_path

app/views/abouts/index.html.slim
h1.head Об организации

- @abouts.each do |about|
  .art-cle
    .para
      = about.text.html_safe

app/views/abouts/new.html.slim
h1 New about

== render 'form'

= link_to 'Back', abouts_path

app/views/abouts/show.html.slim
p#notice = notice

p
  strong Text:
  = @about.text

= link_to 'Edit', edit_about_path(@about)
'|
= link_to 'Back', abouts_path

app/views/admin/abouts/_form.html.slim
= form_for @about do |f|
  - if @about.errors.any?
    #error_explanation
      h2 = "#{pluralize(@about.errors.count, "error")} prohibited this about from being saved:"
      ul
        - @about.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :text
    = f.cktext_area :text, :ckeditor => {:language => 'ru'}
  .actions = f.submit 'Save'

app/views/news/_form.html.slim
= form_for @news do |f|
  - if @news.errors.any?
    #error_explanation
      h2 = "#{pluralize(@news.errors.count, "error")} prohibited this news from being saved:"
      ul
        - @news.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :autor
    = f.text_field :autor
  .field
    = f.label :text
    = f.text_area :text
  .actions = f.submit 'Save'

app/views/news/edit.html.slim
h1 Editing news

== render 'form'

= link_to 'Show', @news
'|
= link_to 'Back', news_path

app/views/news/index.html.slim
h1.head Новости

- @news.each do |news|
  .art-cle
    h2.title
      = news.title
    .para
      = truncate_html news.text, length: 250, omission: '...'
    .more
      = link_to 'Далее >>', news_path(news)

app/views/news/new.html.slim
h1 New news

== render 'form'

= link_to 'Back', news_path

app/views/news/show.html.slim
p#notice = notice

h2.title.news
  = @news.title
.para-news
  = raw @news.text

/= link_to 'Edit', edit_news_path(@news)
.more
  = link_to '<< Назад', news_index_path

app/views/yarns/_form.html.slim
= form_for @yarn do |f|
  - if @yarn.errors.any?
    #error_explanation
      h2 = "#{pluralize(@yarn.errors.count, "error")} prohibited this yarn from being saved:"
      ul
        - @yarn.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :text
    = f.text_area :text
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :autor
    = f.text_field :autor
  .actions = f.submit 'Save'

app/views/yarns/edit.html.slim
h1 Editing yarn

== render 'form'

= link_to 'Show', @yarn
'|
= link_to 'Back', yarns_path

app/views/yarns/index.html.slim
h1.head Полиэфирные нити
.desc ОАО «Тверской Полиэфир» производит нити полиэфирные пневмотекстурированные (ATY) и фрикционнотекстурированные (DTY) неокрашенные, окрашенные в массе и меланжевые. Крашение в массе обеспечивает выпуск многотоннажных партий нити без разнотона, высокую устойчивость окраски к свету и физико-химическим воздействиям. Цветовая гамма окрашенных в массе нитей представлена в карте цветов. Существует возможность осуществлять подбор цвета по образцу нити или ткани. Срок исполнения заказа по разработке цвета до 2 месяцев при наличии заказа от 3 тонн. Помимо собственных разработок меланжированных нитей, ОАО «Тверской Полиэфир» готов разрабатывать «меланжи» по заданию потребителей.
br
br

- @yarns.each do |yarns|
  h2.title.titleya
    = yarns.title
  .art-cleya
    .para
      = truncate_html yarns.text, length: 350, omission: '...'
    .moreya
      = link_to 'Подробнее', yarn_path(yarns)

app/views/yarns/new.html.slim
h1 New yarn

== render 'form'

= link_to 'Back', yarns_path

app/views/yarns/show.html.slim
p#notice = notice

h2.title.news
  = @yarn.title
.para-news
  = @yarn.text.html_safe

/= link_to 'Edit', edit_news_path(@news)
.more
  = link_to '<< Назад', yarns_path