config/routes.rb
Polyester::Application.routes.draw do

  get 'pages/claim'
  post 'pages/access'
  get 'pages/products'

  mount Ckeditor::Engine => '/ckeditor'

  resources :vendors, :contacts, :abouts, only: [:index]
  resources :mebels, :cloths, :yarns, :news, only: [:index, :show]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'news#index'

  

end

app/models/about.rb
class About < ActiveRecord::Base
  attr_accessible :text
  has_many :image
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :name, :login, :password, :password_confirmation, :current_sign_in_at, :last_sign_in_at
end

app/models/cloth.rb
class Cloth < ActiveRecord::Base
  attr_accessible :text, :autor, :title
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :text
  has_many :image
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :about
  belongs_to :contact
  belongs_to :vendor
end

app/models/mebel.rb
class Mebel < ActiveRecord::Base
  attr_accessible :text, :autor, :title
end

app/models/new.rb
class New < ActiveRecord::Base
  attr_accessible :text, :autor, :title
end

app/models/page.rb
class Page < ActiveRecord::Base
  validates :mail, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create }, :presence => true
  validates :name, :presence => true
  validates :message, :presence => true
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  attr_accessible :text
  has_many :image
end

app/models/yarn.rb
class Yarn < ActiveRecord::Base
  attr_accessible :text, :autor, :title
end

app/controllers/mebels_controller.rb
class MebelsController < InheritedResources::Base
end

app/controllers/news_controller.rb
class NewsController < InheritedResources::Base
  def index
    @news=New.all
  end

  def show
    @news = New.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < InheritedResources::Base

  def claim
    render 'claim'
  end

  def access
    Pony.mail(:to => 'darkwater666@mail.ru', :from => 'me@example.com', :subject => 'hi', :body => params[:message], :via => :smtp) # sends via SMTP
    render 'access'
  end

  def products
    render 'products'
  end

end

app/controllers/yarns_controller.rb
class YarnsController < InheritedResources::Base
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cloths_helper.rb
module ClothsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/mebels_helper.rb
module MebelsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/yarns_helper.rb
module YarnsHelper
end

app/views/mebels/_form.html.slim
= form_for @mebel do |f|
  - if @mebel.errors.any?
    #error_explanation
      h2 = "#{pluralize(@mebel.errors.count, "error")} prohibited this mebel from being saved:"
      ul
        - @mebel.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :text
    = f.text_area :text
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :autor
    = f.text_field :autor
  .actions = f.submit 'Save'

app/views/mebels/edit.html.slim
h1 Editing mebel

== render 'form'

= link_to 'Show', @mebel
'|
= link_to 'Back', mebels_path

app/views/mebels/index.html.slim
h1.head Мебельные ткани
//.desc ОАО «Тверской Полиэфир» производит нити полиэфирные пневмотекстурированные (ATY) и фрикционнотекстурированные (DTY) неокрашенные, окрашенные в массе и меланжевые. Крашение в массе обеспечивает выпуск многотоннажных партий нити без разнотона, высокую устойчивость окраски к свету и физико-химическим воздействиям. Цветовая гамма окрашенных в массе нитей представлена в карте цветов. Существует возможность осуществлять подбор цвета по образцу нити или ткани. Срок исполнения заказа по разработке цвета до 2 месяцев при наличии заказа от 3 тонн. Помимо собственных разработок меланжированных нитей, ОАО «Тверской Полиэфир» готов разрабатывать «меланжи» по заданию потребителей.
br
br

- @mebels.each do |mebel|
  h2.title.titleya
    = mebel.title
  .art-cleya
    .para
      = truncate_html mebel.text, length: 1400, omission: '...'
    .moreya
      = link_to 'Подробнее', mebel_path(mebel)

app/views/mebels/new.html.slim
h1 New mebel

== render 'form'

= link_to 'Back', mebels_path

app/views/mebels/show.html.slim
p#notice = notice

h2.title.news
  = @mebel.title
.para-news
  = @mebel.text.html_safe

/= link_to 'Edit', edit_news_path(@news)
.more
  = link_to '<< Назад', mebels_path