config/routes.rb
Polyester::Application.routes.draw do

  get 'pages/claim'
  post 'pages/access'
  get 'pages/products'

  mount Ckeditor::Engine => '/ckeditor'

  resources :vendors, :contacts, :abouts, only: [:index]
  resources :mebels, :cloths, :yarns, :news, only: [:index, :show]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'news#index'

  

end

app/models/about.rb
class About < ActiveRecord::Base
  attr_accessible :text
  has_many :image
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :name, :login, :password, :password_confirmation, :current_sign_in_at, :last_sign_in_at
end

app/models/cloth.rb
class Cloth < ActiveRecord::Base
  attr_accessible :text, :autor, :title
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :text
  has_many :image
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :about
  belongs_to :contact
  belongs_to :vendor
end

app/models/mebel.rb
class Mebel < ActiveRecord::Base
  attr_accessible :text, :autor, :title
end

app/models/new.rb
class New < ActiveRecord::Base
  attr_accessible :text, :autor, :title
end

app/models/page.rb
class Page < ActiveRecord::Base
  validates :mail, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create }, :presence => true
  validates :name, :presence => true
  validates :message, :presence => true
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  attr_accessible :text
  has_many :image
end

app/models/yarn.rb
class Yarn < ActiveRecord::Base
  attr_accessible :text, :autor, :title
end

app/controllers/news_controller.rb
class NewsController < InheritedResources::Base
  def index
    @news=New.all
  end

  def show
    @news = New.find(params[:id])
  end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cloths_helper.rb
module ClothsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/mebels_helper.rb
module MebelsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/yarns_helper.rb
module YarnsHelper
end

app/views/layouts/_links.slim
ul
  li
    = link_to 'Об организации', abouts_path, :class => 'link_about'
  li
    = link_to 'Новости', root_path, :class => 'link_news'
  li
    = link_to 'Ассортимент продукции', pages_products_path, :class => 'link_products'
  li
    = link_to 'Сделать заявку', pages_claim_path, :class => 'link_form'
  li
    = link_to 'Контакты', contacts_path, :class => 'link_contacts'
  li
    = link_to 'Поставщикам', vendors_path, :class => 'link_vendors'

app/views/layouts/application.slim
DOCTYPE html
html
head
  title Тверской полиэфир
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = stylesheet_link_tag    'polyester', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = javascript_include_tag 'system', 'data-turbolinks-track' => true
  = csrf_meta_tags
body
p.notice
  = notice
p.alert
  = alert
#main-site
  #header-site
    .left-site
    .right-site
      .logo-site
        a href='/' title='На главную'
          .logolink
      .menu-site
        = render 'layouts/links.slim'
  #body-site
    .leftbar
      = render 'layouts/links.slim'
      ul.docs
        li
          = link_to 'Раскрытие информации эмитентом', '#', :class => 'link_docs'
    .mainwin
      .topsqw
      .article
        = yield
      .botsqw
  #footer-site
    .foot-left
    .foot-right
      .foot-menu
        = render 'layouts/links.slim'
      .foot-splash

app/views/pages/_form.html.slim
= form_for @page do |f|
  - if @page.errors.any?
    #error_explanation
      h2 = "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      ul
        - @page.errors.full_messages.each do |message|
          li = message

  .actions = f.submit 'Save'

app/views/pages/access.slim
.access
  Спасибо за отправку письма!

app/views/pages/claim.slim
h1.head Сделать заявку

.art-cle
  .para
    p style="text-align:justify" Минимальная партия продажи нити стандартного ассотримента - 1 коробка
    p style="text-align:justify" &nbsp;
    p style="text-align:justify" Минимальная партия продажи полиэфирной ткани, триплированный ткани - 1 рулон.
    p style="text-align:justify" &nbsp;
    p style="text-align:justify" По согласованию с потребителем можем произвести продажу 1 бобины нити.
    p style="text-align:justify" &nbsp;
    h3 style="text-align:justify; color: #F00 !important;" ПРОДАЖИ ПОЛИЭФИРНОЙ НИТИ И ТКАНИ
    p style="text-align:justify" &nbsp;
  .parall
    table border="0" cellpadding="0" cellspacing="0" style="color:rgb(81, 81, 81); font-family:verdana,arial,helvetica,sans-serif; font-size:0.8em; line-height:normal; text-align:justify; width:100%; margin-lef: 20px;"
      tbody
        tr
          td
            h4 НАЧАЛЬНИК ДЕПАРТАМЕНТА ПРОДАЖ:
          td
            h4 МАРИЩУК ВЛАДИМИР БОРИСОВИЧ
        tr
          td
            h4 ТЕЛЕФОН/ФАКС:
          td
            h4 ТЕЛ: (4822) 34 93 70
        tr
          td
            h4 &nbsp;
          td
            h4 МОБ: +7 920 687 12 12
        tr
          td
            h4 —
          td
            h4 —
        tr
          td
            h4 Е-MAIL
          td
            h4 SALES@POLYESTER.RU

    p style='text-align:justify' &nbsp;
    p style='text-align:justify' &nbsp;
  .para
    p style='text-align:justify' Связаться со специалистом Вы можете также через прилагаемую форму
    p style='text-align:justify' &nbsp;
    p style='text-align:justify' &nbsp;
    table.mails
      tbody
        = form_tag pages_access_path do
          tr
            td.mailstd
              = label_tag  'Контактное лицо:'
            td
              = text_field_tag 'name'
          tr
            td.mailstd
              = label_tag 'Организация:'
            td
              = text_field_tag 'company'
          tr
            td.mailstd
              = label_tag 'Телефон:'
            td
              = text_field_tag 'tel'
          tr
            td.mailstd
              = label_tag 'e-mail:'
            td
              = text_field_tag 'mail'
          tr
            td.mailstd
              = label_tag 'Сообщение:'
            td
              = text_area_tag 'massage', nil, :rows => 6, :cols => 30
          tr
            td.mailstd
            td
              /= show_simple_captcha
          tr
            td.mailstd
            td
              = submit_tag 'Отправить'
        end

app/views/pages/edit.html.slim
h1 Editing page

== render 'form'

= link_to 'Show', @page
'|
= link_to 'Back', pages_path

app/views/pages/index.html.slim
h1 Listing pages

table
  tr
    th
    th
    th

  - @pages.each do |page|
    tr
      td = link_to 'Show', page
      td = link_to 'Edit', edit_page_path(page)
      td = link_to 'Destroy', page, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Page', new_page_path

app/views/pages/new.html.slim
h1 New page

== render 'form'

= link_to 'Back', pages_path

app/views/pages/products.slim
h1.head Ассортимент продукции

.art-clesbig
  .paralinksbig
    ul
      li
        = link_to 'ПОЛИЭФИРНЫЕ НИТИ', yarns_path, :class => 'link_nit'
        br
        span от 70 руб/кг с НДС
      li
        = link_to 'ПОЛИЭФИРНЫЕ ТКАНИ', cloths_path, :class => 'link_tkan'
        br
        span от 35 руб/кв.м с НДС
      li
        = link_to 'МЕБЕЛЬНЫЕ ТКАНИ', mebels_path, :class => 'link_mebel'
        br
        span Рогожка из меланжевых нитей собственного производства
.art-cles
  .paralinks
    ul
      li
        = link_to 'Х-НИТЬ', '#', :class => 'link_nit'
      li
        = link_to 'ОТХОДЫ ПРОИЗВОДСТВА ПОЛИЭФИРНОЙ НИТИ И ТКАНИ', '#', :class => 'link_tkan'
      li
        = link_to 'НИТЬ ПОЛИЭФИРНАЯ ТЕКСТУРИРОВАННАЯ ШВЕЙНАЯ', '#', :class => 'link_mebel'
      li
        = link_to 'НИТЬ ПОЛИЭФИРНАЯ ДЛЯ ПРОШИВА МЕШКОВ', '#', :class => 'link_mebel'
      li
        = link_to 'НИТЬ ПОЛИЭФИРНАЯ ТЕКСТУРИРОВАННАЯ ДЛЯ ОВЕРЛОКА', '#', :class => 'link_mebel'
      li
        = link_to 'НИТЬ ЛАТЕКСНАЯ ОПЛЕТЕННАЯ', '#', :class => 'link_mebel'
      li
        = link_to 'МАТЕРИАЛ ТРИПЛИРОВАННЫЙ ОБИВОЧНЫЙ', '#', :class => 'link_mebel'

app/views/pages/show.html.slim
p#notice = notice


= link_to 'Edit', edit_page_path(@page)
'|
= link_to 'Back', pages_path